import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import NavBar from "./components/NavBar";
import styles from "./globals.module.css";
import AccountProfile from "./components/AccountProfile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${inter.className} ${styles.body}`}>
          
          <AccountProfile styles={{MainNav: styles.MainNav, MainNavText: styles.MainNavText}}/>
          
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
